# Generated by Django 4.1.7 on 2023-04-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registrar", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="new_user",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("confirm_password", models.CharField(max_length=100)),
            ],
        ),
    ]
