# Generated by Django 4.1.7 on 2023-04-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lawyer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=50)),
            ],
        ),
    ]
