# Generated by Django 4.1.7 on 2023-04-08 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.IntegerField(default=0),
        ),
    ]
